FROM ubuntu
ARG TARGETPLATFORM linux/x86_64
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ="America/New_York"
ENV SHELL /bin/bash
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    wget \
    build-essential \
    g++ \
    git \
    unzip \
    python3 \
    cpanminus \
    python3-pip \
    python3-dev \
    ncbi-entrez-direct

